### ISSUE TITLE
daa-meganizer killed at line 44

### ISSUE THREAD

**Issue by Mayurk619** [husonlab/megan-ce#19]
daa-meganizer writing always gets killed at 80%. I ran my job on HPC cluster with daa file of 27 GB and allocated 50GB RAM to daa-meganizer. I am not able to find a solution for this anywhere.

**Comment by IdoBar** [comment]
According to [this comment](https://megan.cs.uni-tuebingen.de/t/meganizing-stuck-at-writing-80/2121/10) on the community board, this issue should be solved in the next release (which was supposed to be released a couple of days ago).

**Comment by husonlab** [comment]
Release 6.25.1 should work without this problem

**Comment by IdoBar** [comment]
Thanks @husonlab, 
When can we expect this release?
